name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - ROS_DISTRO: foxy
            ROS_REPO: main
            AFTER_INIT_EMBED: "ici_source_setup /opt/moveit2/install"
            TARGET_CMAKE_ARGS: "-DCMAKE_C_FLAGS='--coverage' -DCMAKE_CXX_FLAGS='--coverage'"
            AFTER_SCRIPT: "./coverage.sh ci"
            ISOLATION: "shell" 
    env:
      CCACHE_DIR: /github/home/.ccache 
    runs-on: ubuntu-20.04
    container:
      image: docker://tanjpg/easy_manipulation_deployment:ci
    steps:
      - uses: actions/checkout@v2
      # step up caching
      - uses: actions/cache@v2
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.env.ROS_DISTRO }}-${{ matrix.env.ROS_REPO }}
      # Run industrial_ci
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
      - uses: codecov/codecov-action@v1
        with:
          files: ./coverage.info
          fail_ci_if_error: true
